spring:
  application:
    name: pagos-socios
  data:
    cassandra:
      keyspace-name: pagos_socios
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
      local-datacenter: datacenter1


server:
  port: 8097
man-socios:
  ribbon:
    listOfServers: localhost:8092,localhost:8093,localhost:8094
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
            defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost     
    


